# Learn more about configuring your app at:
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "TEMPLATE_APP_NAME"
application_url = "https://TEMPLATE_APP_URL"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_products,read_inventory,write_inventory,read_customers,read_companies,write_companies,read_draft_orders,write_draft_orders,read_orders"

[auth]
redirect_urls = [ "https://TEMPLATE_APP_URL/api/auth" ]

[app_proxy]
url = "https://TEMPLATE_APP_URL/api/proxy/TEMPLATE_APP_KEY"
subpath = "TEMPLATE_APP_KEY"
prefix = "a"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/draft_orders/update"
  topics = [ "draft_orders/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_items/update"
  topics = [ "inventory_items/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]
